# Generated by Django 3.1.7 on 2021-05-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
