# Generated by Django 3.1.7 on 2021-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0003_auto_20210520_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
