# Generated by Django 3.1.7 on 2021-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0004_auto_20210520_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='ordersarchive',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersarchive',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersarchive',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersarchive',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
