# Generated by Django 3.1.7 on 2021-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0005_auto_20210520_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rate',
        ),
        migrations.AddField(
            model_name='ordersarchive',
            name='rate',
            field=models.IntegerField(default=5),
        ),
    ]
