# Generated by Django 3.1.7 on 2021-05-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0007_auto_20210520_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
