# Generated by Django 3.1.7 on 2021-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0008_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='salary',
            field=models.FloatField(default=3000),
        ),
        migrations.AlterField(
            model_name='car',
            name='cost_per_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalbase',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='repairments',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
