# Generated by Django 3.1.7 on 2021-05-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0009_auto_20210527_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersarchive',
            name='rate',
        ),
    ]
